### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by AIWintermuteAI** [espressif/esp-nn#2]
Hello!
I've tested optimized kernels for plain ESP32 and got very nice performance boost! Good job!
A little organizational question - do you plan to have releases published? For my project, all the components will be automatically obtained with ```git clone``` and in order to ensure stable builds either release or branch number is preferred. I could use a commit number too, but that would be less convenient. I'm sure other people using ESP-NN also would appreciate having versioned releases.

**Comment by vikramdattu** [comment]
Hi @AIWintermuteAI release sure is under consideration and will be tagged soon.

**Comment by nliaudat** [comment]
any up ?

**Comment by vikramdattu** [comment]
Hi @nliaudat you can use following tag: [v1.0-beta](https://github.com/espressif/esp-nn/releases/tag/v1.0-beta)

**Comment by kedars** [comment]
https://github.com/espressif/esp-nn/releases/tag/v1.0-beta

**Comment by nliaudat** [comment]
many thanks !
Regards
